slice_name: NJ City-Level Cost Heatmap
description: null
certified_by: null
certification_details: null
viz_type: treemap_v2
params:
  datasource: 29__table
  viz_type: treemap_v2
  slice_id: 209
  matrixify_show_column_headers: true
  matrixify_mode_columns: metrics
  matrixify_dimension_selection_mode_columns: members
  matrixify_dimension_columns:
    dimension: ''
    values: []
  matrixify_topn_value_columns: 10
  matrixify_topn_order_columns: desc
  matrixify_show_row_labels: true
  matrixify_mode_rows: metrics
  matrixify_dimension_selection_mode_rows: members
  matrixify_dimension_rows:
    dimension: ''
    values: []
  matrixify_topn_value_rows: 10
  matrixify_topn_order_rows: desc
  matrixify_row_height: 300
  matrixify_fit_columns_dynamically: true
  matrixify_charts_per_row: 4
  groupby:
  - prscrbr_city
  metric:
    expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: city_total_cost
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 826
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DECIMAL
      type_generic: 0
      uuid: 2c54106f-9813-47d7-801e-c6a8381a9abf
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: true
    label: City Total Cost
    optionName: metric_h0yfpgdscno_ox5zxhrtdn
  row_limit: 1000
  adhoc_filters: []
  color_scheme: supersetColors
  show_labels: true
  show_upper_labels: true
  label_type: key_value
  number_format: SMART_NUMBER
  currency_format:
    symbol: USD
    symbolPosition: prefix
  date_format: smart_date
  extra_form_data: {}
  dashboards:
  - 12
query_context: '{"datasource":{"id":29,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["prscrbr_city"],"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"city_total_cost","description":null,"expression":null,"filterable":true,"groupby":true,"id":826,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"uuid":"2c54106f-9813-47d7-801e-c6a8381a9abf","verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"City
  Total Cost","optionName":"metric_h0yfpgdscno_ox5zxhrtdn"}],"annotation_layers":[],"row_limit":1000,"series_limit":0,"group_others_when_limit_reached":false,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"29__table","viz_type":"treemap_v2","slice_id":209,"matrixify_show_column_headers":true,"matrixify_mode_columns":"metrics","matrixify_dimension_selection_mode_columns":"members","matrixify_dimension_columns":{"dimension":"","values":[]},"matrixify_topn_value_columns":10,"matrixify_topn_order_columns":"desc","matrixify_show_row_labels":true,"matrixify_mode_rows":"metrics","matrixify_dimension_selection_mode_rows":"members","matrixify_dimension_rows":{"dimension":"","values":[]},"matrixify_topn_value_rows":10,"matrixify_topn_order_rows":"desc","matrixify_row_height":300,"matrixify_fit_columns_dynamically":true,"matrixify_charts_per_row":4,"groupby":["prscrbr_city"],"metric":{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"city_total_cost","description":null,"expression":null,"filterable":true,"groupby":true,"id":826,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"uuid":"2c54106f-9813-47d7-801e-c6a8381a9abf","verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"City
  Total Cost","optionName":"metric_h0yfpgdscno_ox5zxhrtdn"},"row_limit":1000,"adhoc_filters":[],"color_scheme":"supersetColors","show_labels":true,"show_upper_labels":true,"label_type":"key_value","number_format":"SMART_NUMBER","currency_format":{"symbol":"USD","symbolPosition":"prefix"},"date_format":"smart_date","extra_form_data":{},"dashboards":[12],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 7b0c7f94-c8f7-463e-9916-45ff660f7e16
version: 1.0.0
dataset_uuid: 151c2e67-3d9f-418c-bbbd-9f4373b912fe
