slice_name: Prescriber Specialty Cost Ranking
description: null
certified_by: null
certification_details: null
viz_type: pivot_table_v2
params:
  datasource: 35__table
  viz_type: pivot_table_v2
  slice_id: 215
  matrixify_show_column_headers: true
  matrixify_mode_columns: metrics
  matrixify_dimension_selection_mode_columns: members
  matrixify_dimension_columns:
    dimension: ''
    values: []
  matrixify_topn_value_columns: 10
  matrixify_topn_order_columns: desc
  matrixify_show_row_labels: true
  matrixify_mode_rows: metrics
  matrixify_dimension_selection_mode_rows: members
  matrixify_dimension_rows:
    dimension: ''
    values: []
  matrixify_topn_value_rows: 10
  matrixify_topn_order_rows: desc
  matrixify_row_height: 300
  matrixify_fit_columns_dynamically: true
  matrixify_charts_per_row: 4
  groupbyColumns:
  - cost_category
  groupbyRows:
  - specialty
  temporal_columns_lookup: {}
  metrics:
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: prescriber_count
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 867
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: LONGINTEGER
      type_generic: 0
      uuid: c238f9b1-ad59-43d0-b509-f88859d3d22e
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Prescriber Count
    optionName: metric_c1b43g9jj5_i47a40is7zs
    sqlExpression: null
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: total_cost
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 868
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DECIMAL
      type_generic: 0
      uuid: 9f9c361b-1921-4af3-b0b2-287927d17a66
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Total Cost
    optionName: metric_g5702ux77ph_29jndh81n3i
    sqlExpression: null
  metricsLayout: COLUMNS
  adhoc_filters: []
  series_limit: 25
  row_limit: 50
  order_desc: true
  aggregateFunction: Sum
  valueFormat: SMART_NUMBER
  date_format: smart_date
  rowOrder: key_a_to_z
  colOrder: key_a_to_z
  conditional_formatting: []
  allow_render_html: true
  extra_form_data: {}
  dashboards:
  - 12
query_context: '{"datasource":{"id":35,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["cost_category","specialty"],"metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"prescriber_count","description":null,"expression":null,"filterable":true,"groupby":true,"id":867,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"LONGINTEGER","type_generic":0,"uuid":"c238f9b1-ad59-43d0-b509-f88859d3d22e","verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Prescriber
  Count","optionName":"metric_c1b43g9jj5_i47a40is7zs","sqlExpression":null},{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"total_cost","description":null,"expression":null,"filterable":true,"groupby":true,"id":868,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"uuid":"9f9c361b-1921-4af3-b0b2-287927d17a66","verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Total
  Cost","optionName":"metric_g5702ux77ph_29jndh81n3i","sqlExpression":null}],"orderby":[[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"prescriber_count","description":null,"expression":null,"filterable":true,"groupby":true,"id":867,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"LONGINTEGER","type_generic":0,"uuid":"c238f9b1-ad59-43d0-b509-f88859d3d22e","verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Prescriber
  Count","optionName":"metric_c1b43g9jj5_i47a40is7zs","sqlExpression":null},false]],"annotation_layers":[],"row_limit":50,"series_limit":25,"group_others_when_limit_reached":false,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"35__table","viz_type":"pivot_table_v2","slice_id":215,"matrixify_show_column_headers":true,"matrixify_mode_columns":"metrics","matrixify_dimension_selection_mode_columns":"members","matrixify_dimension_columns":{"dimension":"","values":[]},"matrixify_topn_value_columns":10,"matrixify_topn_order_columns":"desc","matrixify_show_row_labels":true,"matrixify_mode_rows":"metrics","matrixify_dimension_selection_mode_rows":"members","matrixify_dimension_rows":{"dimension":"","values":[]},"matrixify_topn_value_rows":10,"matrixify_topn_order_rows":"desc","matrixify_row_height":300,"matrixify_fit_columns_dynamically":true,"matrixify_charts_per_row":4,"groupbyColumns":["cost_category"],"groupbyRows":["specialty"],"temporal_columns_lookup":{},"metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"prescriber_count","description":null,"expression":null,"filterable":true,"groupby":true,"id":867,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"LONGINTEGER","type_generic":0,"uuid":"c238f9b1-ad59-43d0-b509-f88859d3d22e","verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Prescriber
  Count","optionName":"metric_c1b43g9jj5_i47a40is7zs","sqlExpression":null},{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"total_cost","description":null,"expression":null,"filterable":true,"groupby":true,"id":868,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"uuid":"9f9c361b-1921-4af3-b0b2-287927d17a66","verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Total
  Cost","optionName":"metric_g5702ux77ph_29jndh81n3i","sqlExpression":null}],"metricsLayout":"COLUMNS","adhoc_filters":[],"series_limit":25,"row_limit":50,"order_desc":true,"aggregateFunction":"Sum","valueFormat":"SMART_NUMBER","date_format":"smart_date","rowOrder":"key_a_to_z","colOrder":"key_a_to_z","conditional_formatting":[],"allow_render_html":true,"extra_form_data":{},"dashboards":[12],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 36fe7513-879e-4957-b8cc-40613dfff260
version: 1.0.0
dataset_uuid: 0d0dd46a-d053-466e-86ac-258ed01d7c9a
