slice_name: Prescriber Efficiency Scatter
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_scatter
params:
  datasource: 34__table
  viz_type: echarts_timeseries_scatter
  slice_id: 214
  matrixify_show_column_headers: true
  matrixify_mode_columns: metrics
  matrixify_dimension_selection_mode_columns: members
  matrixify_dimension_columns:
    dimension: ''
    values: []
  matrixify_topn_value_columns: 10
  matrixify_topn_order_columns: desc
  matrixify_show_row_labels: true
  matrixify_mode_rows: metrics
  matrixify_dimension_selection_mode_rows: members
  matrixify_dimension_rows:
    dimension: ''
    values: []
  matrixify_topn_value_rows: 10
  matrixify_topn_order_rows: desc
  matrixify_row_height: 300
  matrixify_fit_columns_dynamically: true
  matrixify_charts_per_row: 4
  x_axis: gdr
  x_axis_sort_asc: true
  metrics:
  - aggregate: AVG
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: cost_per_claim
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 861
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: column
      type_generic: 0
      uuid: 60dc4e4d-c883-4a83-a24f-2d2fb6d1f083
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: AVG(cost_per_claim)
    optionName: metric_a2xxgv2tewd_a5i53hndw27
    sqlExpression: null
  groupby:
  - prscrbr_type
  contributionMode: null
  adhoc_filters: []
  order_desc: true
  row_limit: 1000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  x_axis_title: Generic Dispensing Rate
  x_axis_title_margin: 30
  y_axis_title: Cost Per Claim
  y_axis_title_margin: 30
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_number_format: SMART_NUMBER
  xAxisLabelInterval: auto
  rich_tooltip: true
  showTooltipTotal: true
  showTooltipPercentage: false
  tooltipTimeFormat: smart_date
  y_axis_format: SMART_NUMBER
  truncateXAxis: true
  extra_form_data: {}
  dashboards:
  - 12
query_context: '{"datasource":{"id":34,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[{"columnType":"BASE_AXIS","sqlExpression":"gdr","label":"gdr","expressionType":"SQL","isColumnReference":true},"prscrbr_type"],"metrics":[{"aggregate":"AVG","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"cost_per_claim","description":null,"expression":null,"filterable":true,"groupby":true,"id":861,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"column","type_generic":0,"uuid":"60dc4e4d-c883-4a83-a24f-2d2fb6d1f083","verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"AVG(cost_per_claim)","optionName":"metric_a2xxgv2tewd_a5i53hndw27","sqlExpression":null}],"orderby":[[{"aggregate":"AVG","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"cost_per_claim","description":null,"expression":null,"filterable":true,"groupby":true,"id":861,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"column","type_generic":0,"uuid":"60dc4e4d-c883-4a83-a24f-2d2fb6d1f083","verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"AVG(cost_per_claim)","optionName":"metric_a2xxgv2tewd_a5i53hndw27","sqlExpression":null},false]],"annotation_layers":[],"row_limit":1000,"series_columns":["prscrbr_type"],"series_limit":0,"group_others_when_limit_reached":false,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["gdr"],"columns":["prscrbr_type"],"aggregates":{"AVG(cost_per_claim)":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"rename","options":{"columns":{"AVG(cost_per_claim)":null},"level":0,"inplace":true}},{"operation":"flatten"}]}],"form_data":{"datasource":"34__table","viz_type":"echarts_timeseries_scatter","slice_id":214,"matrixify_show_column_headers":true,"matrixify_mode_columns":"metrics","matrixify_dimension_selection_mode_columns":"members","matrixify_dimension_columns":{"dimension":"","values":[]},"matrixify_topn_value_columns":10,"matrixify_topn_order_columns":"desc","matrixify_show_row_labels":true,"matrixify_mode_rows":"metrics","matrixify_dimension_selection_mode_rows":"members","matrixify_dimension_rows":{"dimension":"","values":[]},"matrixify_topn_value_rows":10,"matrixify_topn_order_rows":"desc","matrixify_row_height":300,"matrixify_fit_columns_dynamically":true,"matrixify_charts_per_row":4,"x_axis":"gdr","x_axis_sort_asc":true,"metrics":[{"aggregate":"AVG","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"cost_per_claim","description":null,"expression":null,"filterable":true,"groupby":true,"id":861,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"column","type_generic":0,"uuid":"60dc4e4d-c883-4a83-a24f-2d2fb6d1f083","verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"AVG(cost_per_claim)","optionName":"metric_a2xxgv2tewd_a5i53hndw27","sqlExpression":null}],"groupby":["prscrbr_type"],"contributionMode":null,"adhoc_filters":[],"order_desc":true,"row_limit":1000,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"x_axis_title":"Generic
  Dispensing Rate","x_axis_title_margin":30,"y_axis_title":"Cost Per Claim","y_axis_title_margin":30,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"supersetColors","show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_number_format":"SMART_NUMBER","xAxisLabelInterval":"auto","rich_tooltip":true,"showTooltipTotal":true,"showTooltipPercentage":false,"tooltipTimeFormat":"smart_date","y_axis_format":"SMART_NUMBER","truncateXAxis":true,"extra_form_data":{},"dashboards":[12],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 6728a451-5202-40bd-84f4-db7b93321014
version: 1.0.0
dataset_uuid: 8e1e8584-271f-4232-9eb8-72ef13879efa
